services:
  postgres:
    image: postgres:latest
    container_name: url_container
    environment: 
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    restart: always 

volumes:
  postgres_data:
